### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rayliao** [rayliao/demo#1]
- [ ] 找些设计稿写一些模板
- [ ] 完善自己的个人网站，CV，可以用上fullpage和一个字一个字出现的效果；
- [ ] blog要加上tag；
- [ ] 完成FreeCodeCamp的学习；
- [ ] 完善百度脑图里的前端工程师，然后根据如D3的图标工具，制作成页面，并添加到个人网站上。
- [x] 学会写测试，单元测试（mocha）

**Comment by rayliao** [comment]
应该系统性的学习某个知识点，持之以恒之。
